"""
Tests for api/main.py — FastAPI wrapper.
analyze_transcript is stubbed at the api.main boundary; request validation,
error mapping, and response shaping are exercised through the real app.
"""

import json

import pytest
from fastapi.testclient import TestClient

import api.main as api_main
from api.main import app
from pipeline.config import EXTRACTION_MODEL

client = TestClient(app, raise_server_exceptions=False)

VALID_TRANSCRIPT = (
    "[10:00:01] AGENT: Thank you for calling TeleCo support, how can I help you today?\n"
    "[10:00:09] CUSTOMER: Hi, I need help understanding a charge on my latest bill.\n"
    "[10:00:20] AGENT: Of course, I can pull up your account and walk through it.\n"
    "[10:00:31] CUSTOMER: Thank you, that explains it.\n"
)


# ── /health ───────────────────────────────────────────────────────────

class TestHealth:
    def test_health_ok(self):
        resp = client.get("/health")
        assert resp.status_code == 200
        body = resp.json()
        assert body["status"] == "ok"
        assert body["model"] == EXTRACTION_MODEL
        assert isinstance(body["client_ready"], bool)
        assert body["uptime_seconds"] >= 0


# ── /summary ──────────────────────────────────────────────────────────

class TestSummary:
    def test_404_when_no_summary_exists(self, monkeypatch, tmp_path):
        monkeypatch.setattr(api_main, "OUTPUT_DIR", tmp_path)
        resp = client.get("/summary")
        assert resp.status_code == 404
        assert "Run the pipeline" in resp.json()["detail"]

    def test_serves_summary_file(self, monkeypatch, tmp_path):
        payload = {
            "meta": {"total_calls_analyzed": 20},
            "kpis": {"fcr_rate_pct": 72.0},
            "phase_avg_seconds": {},
            "distributions": {},
            "cost_levers": {},
        }
        (tmp_path / "summary.json").write_text(json.dumps(payload))
        monkeypatch.setattr(api_main, "OUTPUT_DIR", tmp_path)
        resp = client.get("/summary")
        assert resp.status_code == 200
        assert resp.json()["kpis"]["fcr_rate_pct"] == 72.0


# ── /analyze ──────────────────────────────────────────────────────────

@pytest.fixture
def fake_client(monkeypatch):
    """Ensure the module-level client looks initialised."""
    monkeypatch.setattr(api_main, "_extraction_client", object())


class TestAnalyzeValidation:
    def test_empty_transcript_rejected(self):
        resp = client.post("/analyze", json={"transcript": ""})
        assert resp.status_code == 422

    def test_oversized_transcript_rejected(self):
        resp = client.post("/analyze", json={"transcript": "x" * 50_001})
        assert resp.status_code == 422

    def test_invalid_channel_rejected(self):
        resp = client.post("/analyze", json={"transcript": VALID_TRANSCRIPT, "channel": "email"})
        assert resp.status_code == 422

    def test_invalid_call_date_rejected(self):
        resp = client.post(
            "/analyze", json={"transcript": VALID_TRANSCRIPT, "call_date": "01-06-2026"}
        )
        assert resp.status_code == 422


class TestAnalyzeRouting:
    def test_503_when_client_unavailable(self, monkeypatch):
        monkeypatch.setattr(api_main, "_extraction_client", None)
        resp = client.post("/analyze", json={"transcript": VALID_TRANSCRIPT})
        assert resp.status_code == 503

    def test_502_when_extraction_fails(self, monkeypatch, fake_client):
        monkeypatch.setattr(api_main, "analyze_transcript", lambda c, sp, t: None)
        resp = client.post("/analyze", json={"transcript": VALID_TRANSCRIPT})
        assert resp.status_code == 502

    def test_success_strips_internal_token_keys(self, monkeypatch, fake_client, make_record):
        monkeypatch.setattr(api_main, "analyze_transcript", lambda c, sp, t: make_record())
        resp = client.post(
            "/analyze", json={"transcript": VALID_TRANSCRIPT, "call_id": "api-test-1"}
        )
        assert resp.status_code == 200
        body = resp.json()
        assert body["call_id"] == "api-test-1"
        assert body["extraction"]["fcr_indicator"] is True
        for internal in ("_prompt_tokens", "_completion_tokens", "_total_tokens"):
            assert internal not in body["extraction"]
        assert body["processing_time_seconds"] >= 0

    def test_call_id_autogenerated_when_omitted(self, monkeypatch, fake_client, make_record):
        captured = {}

        def fake_analyze(c, sp, transcript):
            captured.update(transcript)
            return make_record()

        monkeypatch.setattr(api_main, "analyze_transcript", fake_analyze)
        resp = client.post("/analyze", json={"transcript": VALID_TRANSCRIPT})
        assert resp.status_code == 200
        # UUID4 format: 36 chars with hyphens
        assert len(resp.json()["call_id"]) == 36
        assert captured["call_id"] == resp.json()["call_id"]
